<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 5', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-BrKL3j","verticalAlign":"center","background":{"type":"default","color":"","videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-7","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","left":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-Bm66rW","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeIn","Tablet":"fadeInLeft","Mobile":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<!-- wp:gutenverse/team {"elementId":"guten-MjrZ5t","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px"}},"src":{"id":1423,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/nature-sweet-flower-honey-pollen-yellow-new.webp","width":1270,"height":912,"altOriginal":"nature sweet honey"},"altType":"original","lazy":"lazy","name":"Nutritionist","job":"Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.","showSocial":false,"nameColor":{"type":"variable","id":"white"},"nameColorHover":{"type":"variable","id":"white"},"nameTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"weight":"600"},"jobColor":{"type":"variable","id":"white"},"jobColorHover":{"type":"variable","id":"white"},"jobTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"profilePadding":{"Desktop":[],"Tablet":[]},"detailsPadding":{"Desktop":{"unit":"%","dimension":{"right":"15","left":"15"}},"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}}},"profileBorderRadius":{"Desktop":[],"Tablet":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"imgWidth":{"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"420","unit":"px"},"Tablet":{"point":"254","unit":"px"},"Mobile":{"point":"212","unit":"px"}},"hoverBgColor":{"r":102,"g":71,"b":80,"a":0.54}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":50,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-FlD3hM","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeIn","Tablet":"fadeInUp","Mobile":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<!-- wp:gutenverse/team {"elementId":"guten-MbeVaO","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px"}},"src":{"id":1424,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/hand-plant-woman-flower-petal-feet-new.webp","width":1270,"height":850,"altOriginal":"hand plant flower"},"altType":"original","lazy":"lazy","name":"Pedicure","job":"Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.","showSocial":false,"nameColor":{"type":"variable","id":"white"},"nameColorHover":{"type":"variable","id":"white"},"nameTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"weight":"600"},"jobColor":{"type":"variable","id":"white"},"jobColorHover":{"type":"variable","id":"white"},"jobTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"profilePadding":{"Desktop":[],"Tablet":[]},"detailsPadding":{"Desktop":{"unit":"%","dimension":{"right":"15","left":"15"}},"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}}},"profileBorderRadius":{"Desktop":[],"Tablet":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"-10"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"imgWidth":{"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"420","unit":"px"},"Tablet":{"point":"254","unit":"px"},"Mobile":{"point":"212","unit":"px"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":102,"g":71,"b":80,"a":0.54},"hoverContentBorder":{"radius":{"Desktop":[]}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-WuTsHg","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeIn","Tablet":"fadeInRight","Mobile":"fadeInRight"},"duration":"normal","delay":"500"}} -->
<!-- wp:gutenverse/team {"elementId":"guten-B1hc3x","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px"}},"src":{"id":1425,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/people-meal-child-baking-ceremony-infant-new.webp","width":1270,"height":847,"altOriginal":"people baking ceremony"},"altType":"original","lazy":"lazy","name":"Waterlava stone","job":"Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.","showSocial":false,"nameColor":{"type":"variable","id":"white"},"nameColorHover":{"type":"variable","id":"white"},"nameTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"weight":"600"},"jobColor":{"type":"variable","id":"white"},"jobColorHover":{"type":"variable","id":"white"},"jobTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"profilePadding":{"Desktop":[],"Tablet":[]},"detailsPadding":{"Desktop":{"unit":"%","dimension":{"right":"15","left":"15"}},"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}}},"profileBorderRadius":{"Desktop":[],"Tablet":[]},"margin":{"Tablet":{"unit":"px","dimension":{"top":"-10","bottom":"-10"}}},"padding":{"Tablet":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"imgHeight":{"Desktop":{"point":"420","unit":"px"},"Mobile":{"point":"212","unit":"px"}},"imgRotate":{"Mobile":""},"hoverBgColor":{"r":102,"g":71,"b":80,"a":0.54},"nameSpace":{"Desktop":""}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
