<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 2', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-5e9nnt","verticalAlign":"center","background":{"type":"default","color":{"type":"variable","id":"waterlava-third"},"videoPlayOnMobile":false},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"100","left":"10","right":"10","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"40","left":"10"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-dgrmOB","background":{"type":"default","color":{"r":166,"g":189,"b":220,"a":1},"image":{"Desktop":{"id":161,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_XVEZDYZASS.webp"},"Mobile":{"id":161,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_XVEZDYZASS.webp"}},"position":{"Desktop":"top center","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(244, 245, 245, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(12, 12, 12, 0.63)","active":true,"opacity":0.63,"id":2,"offset":"1.000"}]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20","right":"0"}},"Desktop":{"unit":"px","dimension":{"right":"20"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}},"Desktop":[]},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInRight"},"duration":"normal","delay":"100"}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-YS4OxF","space":{"Desktop":{"point":"273","unit":"px"}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-xRUlJL","content":"MASSAGES","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"weight":"800"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-yBrJl6","background":{"type":"default","color":{"r":166,"g":189,"b":220,"a":1},"image":{"Desktop":{"id":162,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_ZTASYNHMPV.webp"},"Mobile":{"id":162,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_ZTASYNHMPV.webp"}},"position":{"Desktop":"center left","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(248, 248, 248, 0)","opacity":0,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(21, 21, 21, 0.63)","active":true,"opacity":0.63,"id":2,"offset":"1.000"}]},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20","right":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Tablet":[],"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"slideInUp","Mobile":"fadeInUp"},"duration":"normal","delay":"300"}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-XuSqUc","space":{"Desktop":{"point":"273","unit":"px"}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-SIuecP","content":"THERAPIES","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"weight":"800"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-isqlVu","background":{"type":"default","color":{"r":166,"g":189,"b":220,"a":1},"image":{"Desktop":{"id":163,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_NTQWZSB6SC.webp"},"Mobile":{"id":163,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_NTQWZSB6SC.webp"}},"position":{"Desktop":"center left","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 0)","opacity":0,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(12, 12, 12, 0.63)","active":true,"opacity":0.63,"id":2,"offset":"1.000"}]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInRight","Mobile":"fadeInRight"},"duration":"normal","delay":"500"}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-LuUZiP","space":{"Desktop":{"point":"273","unit":"px"}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-JP0sjR","content":"RELAXATION","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"weight":"800"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
