<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-4qr4Df","background":{"type":"default","image":{"Desktop":{"id":143,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/nature-plant-leaf-flower-petal-glass-612874-pxhere.com_.webp"}},"position":{"Desktop":"bottom center","Tablet":"center center","Mobile":"center center"},"size":{"Desktop":"cover","Tablet":"cover"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"yposition":{"Tablet":{"point":"1","unit":"px"},"Mobile":{"point":"","unit":"px"}},"xposition":{"Tablet":{"unit":"vh","point":"0.1"},"Mobile":{"unit":"em","point":""}},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-background-overlay"},"gradientColor":[{"color":"rgb(247, 248, 248)","active":false,"opacity":0.53,"id":1,"offset":"0.000"},{"color":"rgb(250, 250, 250)","active":false,"opacity":0,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.7","border":{"radius":{"Tablet":[],"Desktop":[]}},"bottomDivider":{"type":"waves","width":{"Desktop":"144","Tablet":"174"},"flip":false,"height":{"Desktop":"90","Tablet":"100"},"colorMode":"default","color":{"r":255,"g":252,"b":249,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"200"}},"Tablet":{"unit":"px","dimension":{"top":"150","bottom":"200","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"150","bottom":"200"}}},"animation":{"type":{"Desktop":"none"}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-3vgI6y"} -->
<!-- wp:gutenverse/heading {"elementId":"guten-q3mXI6","content":"Beauty Spa, Relaxing \u0026 Wellness Center","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"style":"italic","weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none","Tablet":"none","Mobile":"none"},"duration":"normal","delay":""}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-kxbE7L","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"px","point":"28.8"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"120","top":"0","bottom":"0","left":"120"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40","left":"40"}}},"animation":{"type":{"Desktop":"none","Tablet":"none","Mobile":"none"},"duration":"normal","delay":"100"}} -->
<!-- wp:paragraph -->
<p>Quisque consectetur convallis exquis tincidunt ligula placeratet. Nam quis leo sed tortor blandit commodo. Quisque ultrices justo non convallis accumsan ante magna ornare sapien quis venenatis diam libero necorci.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"elementId":"guten-DPwJel","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-HIN6fa","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/button {"elementId":"guten-i0nEgV","content":"Get Started","url":"#","alignButton":{"Desktop":"right","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"40","left":"40"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-secondary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"white"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","color":{"r":191,"g":164,"b":152,"a":1},"width":"1"}},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"300"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"12"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"ariaLabel":"get started"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-jhBZEQ"} -->
<!-- wp:gutenverse/button {"elementId":"guten-8s3F5w","content":"Book An Appointment","url":"#","alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"40","left":"40"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBorder":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"none","Tablet":"none","Mobile":"none"},"duration":"normal","delay":"200"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"12"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"hoverTextColor":{"type":"variable","id":"gv-color-background-primary"},"ariaLabel":"book an appointment","className":"guten-element guten-button-wrapper guten-8s3F5w elementor-animation-wobble-horizontal"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
