<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 7', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-XbUaxt","background":{"type":"default","color":{"type":"variable","id":"waterlava-secondary"},"videoPlayOnMobile":false},"bottomDivider":{"type":"waves","width":{"Desktop":"117"},"height":{"Desktop":"66"},"flip":false,"colorMode":"default","color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Tablet":[],"Mobile":[],"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"20","bottom":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}},"Desktop":{"unit":"px","dimension":{"bottom":"150"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-4gI64c","margin":{"Desktop":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none","Tablet":"fadeInUp","Mobile":"fadeInUp"},"duration":"normal","delay":""}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-jceONs","border":{"radius":{"Desktop":[]},"bottom":{"type":"dashed","width":"1","color":{"type":"variable","id":"waterlava-primary"}}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":15,"Tablet":20,"Mobile":20},"elementId":"guten-nt0ITT"} -->
<!-- wp:gutenverse/image {"elementId":"guten-EwWJF0","imgSrc":{"media":{"imageId":1265,"sizes":{"thumbnail":{"height":148,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/woman-skin-spa-beauty-nose-neck.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/woman-skin-spa-beauty-nose-neck.webp","height":148,"width":222,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"woman skin spa","captionOriginal":"","width":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Mobile":{"point":"43","unit":"px"},"Tablet":{"point":"85","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[],"Tablet":[]}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"captionSpace":{"Desktop":""},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":85,"Tablet":77.77,"Mobile":77.64},"elementId":"guten-NTny8G","margin":{"Mobile":{"unit":"px","dimension":{"left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"left":""}}}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-mMQkv4","titleTag":"h3","text":"Face Scrub","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"waterlava-primary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"361","unit":"px"},"Tablet":{"point":"588","unit":"px"},"Mobile":{"point":"268","unit":"px"}}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-79oJiI","alignText":{"Desktop":"flex-end"},"titleTag":"h3","text":"$41   ","focusText":"/Hours","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-secondary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-primary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"-60"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-VxEcAb","border":{"radius":{"Desktop":[]},"top":{"type":"none","width":"","color":""},"bottom":{"type":"dashed","width":"1","color":{"type":"variable","id":"waterlava-primary"}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":15,"Tablet":20,"Mobile":20},"elementId":"guten-Gy7eE4"} -->
<!-- wp:gutenverse/image {"elementId":"guten-giyA0j","imgSrc":{"media":{"imageId":1283,"sizes":{"thumbnail":{"height":148,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/waterlava-woman-skincare.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/waterlava-woman-skincare.webp","height":148,"width":222,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"woman skincare","captionOriginal":"","width":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Mobile":{"point":"43","unit":"px"},"Tablet":{"point":"85","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[],"Tablet":[]}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"captionSpace":{"Desktop":""},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":85,"Tablet":77.77,"Mobile":77.64},"elementId":"guten-uOot6c"} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-41tzSH","titleTag":"h3","text":"Face ","focusText":"Mask","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"waterlava-primary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"361","unit":"px"},"Tablet":{"point":"588","unit":"px"},"Mobile":{"point":"268","unit":"px"}}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-GG8UvK","alignText":{"Desktop":"flex-end"},"titleTag":"h3","text":"$37  ","focusText":"/Hours","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-secondary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-primary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10","left":"-60"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-w6Zsco","border":{"radius":{"Tablet":[],"Desktop":[]},"bottom":{"type":"dashed","width":"1","color":{"type":"variable","id":"waterlava-primary"}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":15,"Tablet":20,"Mobile":20},"elementId":"guten-nPYWVL"} -->
<!-- wp:gutenverse/image {"elementId":"guten-eUNf4q","imgSrc":{"media":{"imageId":1445,"sizes":{"thumbnail":{"height":117,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/waterlava-massages-neww.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/waterlava-massages-neww.webp","height":117,"width":176,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"waterlava massage","captionOriginal":"","width":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Mobile":{"point":"43","unit":"px"},"Tablet":{"point":"85","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[],"Tablet":[]}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"captionSpace":{"Desktop":""},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":85,"Tablet":77.77,"Mobile":77.64},"elementId":"guten-RCUBYj"} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-sZiClE","titleTag":"h3","text":"Body Lift","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"waterlava-primary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"361","unit":"px"},"Tablet":{"point":"589","unit":"px"},"Mobile":{"point":"268","unit":"px"}}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-FLK7Uv","alignText":{"Desktop":"flex-end"},"titleTag":"h3","text":"$48 ","focusText":"/Hours","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-secondary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-primary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10","left":"-60"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-e7MsV9","margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none","Tablet":"fadeInRight","Mobile":"slideInRight"},"duration":"normal","delay":""}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-neHeVE","border":{"radius":{"Desktop":[]},"bottom":{"type":"dashed","width":"1","color":{"type":"variable","id":"waterlava-primary"}}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"-5","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"18"}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":15,"Tablet":20,"Mobile":20},"elementId":"guten-wnXlUH"} -->
<!-- wp:gutenverse/image {"elementId":"guten-PZTR9g","imgSrc":{"media":{"imageId":1444,"sizes":{"thumbnail":{"height":105,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/hand-woman-white-female-leg-young-neww.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/hand-woman-white-female-leg-young-neww.webp","height":105,"width":158,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"hand massages","captionOriginal":"","width":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Mobile":{"point":"43","unit":"px"},"Tablet":{"point":"85","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[],"Tablet":[]}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"captionSpace":{"Desktop":""},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":85,"Tablet":77.77,"Mobile":77.64},"elementId":"guten-wcdH8r"} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-17BlOL","titleTag":"h3","text":"Hand \u0026 Feet","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"waterlava-primary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"300","unit":"px"},"Tablet":{"point":"589","unit":"px"},"Mobile":{"point":"268","unit":"px"}},"className":"guten-element guten-advanced-heading guten-17BlOL"} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-7sIOG3","alignText":{"Desktop":"flex-end"},"titleTag":"h3","text":"$42   ","focusText":"/Hours","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-secondary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-primary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10","left":"-60"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-qhXeaT","border":{"radius":{"Desktop":[]},"top":{"type":"none","width":"","color":""},"bottom":{"type":"dashed","width":"1","color":{"type":"variable","id":"waterlava-primary"}}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"-3"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"15","right":"","left":""}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":15,"Tablet":20,"Mobile":20},"elementId":"guten-Me8Lp7"} -->
<!-- wp:gutenverse/image {"elementId":"guten-YX9zdo","imgSrc":{"media":{"imageId":1443,"sizes":{"thumbnail":{"height":105,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/waterlava-woman-skincare-serum-new.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/waterlava-woman-skincare-serum-new.webp","height":105,"width":158,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"serum skincare","captionOriginal":"","width":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Mobile":{"point":"43","unit":"px"},"Tablet":{"point":"85","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[],"Tablet":[]}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"captionSpace":{"Desktop":""},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":85,"Tablet":77.77,"Mobile":77.64},"elementId":"guten-Y3ywKi"} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-H8xo8w","titleTag":"h3","text":"Skin Facial","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"waterlava-primary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"300","unit":"px"},"Tablet":{"point":"589","unit":"px"},"Mobile":{"point":"268","unit":"px"}}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-pQgp1p","alignText":{"Desktop":"flex-end"},"titleTag":"h3","text":"$34  ","focusText":"/Hours","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-secondary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-primary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10","left":"-60"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-44RRZQ","border":{"radius":{"Desktop":[]},"bottom":{"type":"dashed","width":"1","color":{"type":"variable","id":"waterlava-primary"}}},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"18"}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":15,"Tablet":20,"Mobile":20},"elementId":"guten-TJylZp"} -->
<!-- wp:gutenverse/image {"elementId":"guten-71S9OR","imgSrc":{"media":{"imageId":1442,"sizes":{"thumbnail":{"height":105,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/waterlava-woman-bodycare-new.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/waterlava-woman-bodycare-new.webp","height":105,"width":158,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"waterlava bodycare","captionOriginal":"","width":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Mobile":{"point":"43","unit":"px"},"Tablet":{"point":"85","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[],"Tablet":[]}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"captionSpace":{"Desktop":""},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":85,"Tablet":77.77,"Mobile":77.64},"elementId":"guten-uP62zu"} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-fWOg82","titleTag":"h3","text":"Floral Bath","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"waterlava-primary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"300","unit":"px"},"Tablet":{"point":"589","unit":"px"},"Mobile":{"point":"268","unit":"px"}}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-S6a7hc","alignText":{"Desktop":"flex-end"},"titleTag":"h3","text":"$58  ","focusText":"/Hours","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-secondary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"focusColor":{"type":"variable","id":"gv-color-primary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subTypography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Tablet":{"point":"23.4","unit":"px"}}},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10","left":"-60"}},"Tablet":{"unit":"px","dimension":{"left":"20"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
