<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 4', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-hUZiaL","verticalAlign":"center","background":{"type":"default","color":"","videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"0","left":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-RdWIvY","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight","Tablet":"fadeInRight","Mobile":"fadeInRight"},"duration":"normal","delay":"100"}} -->
<!-- wp:gutenverse/team {"elementId":"guten-OYmIYu","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px"}},"src":{"id":31,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/woman-skin-spa-beauty-nose-neck-1604350-pxhere.com_.webp","width":1920,"height":1280,"altOriginal":"woman skin facial"},"altType":"original","lazy":"lazy","name":"Wellness","job":"Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus","showSocial":false,"nameColor":{"type":"variable","id":"white"},"nameColorHover":{"type":"variable","id":"white"},"nameTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"jobColor":{"type":"variable","id":"white"},"jobColorHover":{"type":"variable","id":"white"},"jobTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"profilePadding":{"Desktop":[],"Tablet":[]},"detailsPadding":{"Desktop":[],"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}}},"profileBorderRadius":{"Desktop":[],"Tablet":[]},"profileBorder":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow","delay":"1"},"imgHeight":{"Desktop":{"point":"600","unit":"px"},"Tablet":{"point":"254","unit":"px"},"Mobile":{"point":"212","unit":"px"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":102,"g":71,"b":80,"a":0.54},"hoverContentBorder":{"radius":{"Desktop":[]}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-UAUXFE","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft","Tablet":"fadeInLeft","Mobile":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<!-- wp:gutenverse/team {"elementId":"guten-wNv2Pe","profileType":"overlay","overlayProfilePosition":{"Desktop":{"unit":"px"}},"src":{"id":20,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_VH22RVC5UT.webp","width":1920,"height":1280,"altOriginal":"body massage"},"altType":"original","lazy":"lazy","name":"Treatment","job":"Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus.","showSocial":false,"nameColor":{"type":"variable","id":"white"},"nameColorHover":{"type":"variable","id":"white"},"nameTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"weight":"600"},"jobColor":{"type":"variable","id":"white"},"jobColorHover":{"type":"variable","id":"white"},"jobTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"profilePadding":{"Desktop":[],"Tablet":[]},"detailsPadding":{"Desktop":[],"Tablet":{"unit":"%","dimension":{"right":"15","left":"15"}}},"profileBorderRadius":{"Desktop":[],"Tablet":[]},"profileBorder":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":[]}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"-10"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"slideInLeft"},"duration":"slow","delay":"2"},"imgHeight":{"Desktop":{"point":"600","unit":"px"},"Tablet":{"point":"254","unit":"px"},"Mobile":{"point":"212","unit":"px"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"r":102,"g":71,"b":80,"a":0.54},"hoverContentBorder":{"radius":{"Desktop":[]}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
