<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 3', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-CoqbuA","background":{"type":"default","color":{"type":"variable","id":"waterlava-third"},"videoPlayOnMobile":false},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"left":"10","right":"10"}},"Desktop":{"unit":"px","dimension":{"top":"50","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-dl8OBm","background":{"type":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-k4jsJY","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-bKnrrp","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-7GFvGV","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"40"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-o9lZgK","margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-aZNCj5","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"sectionVerticalAlign":"center","elementId":"guten-7pLije","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-lICvzB","content":"Best Service For You","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"fadeInDown","Mobile":"fadeInRight"},"duration":"normal","delay":""}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-e0HmOv","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"right":"10","left":"10"}}},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInUp"},"delay":"100","duration":"normal"}} -->
<!-- wp:paragraph -->
<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/heading {"elementId":"guten-9yyP9k","content":"S e r v i c e s","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-accent-secondary"},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"200","unit":"px"},"Tablet":{"point":"150","unit":"px"},"Mobile":{"point":"60","unit":"px"}},"weight":"600","transform":"default","spacing":{"Desktop":"0","Tablet":"0"},"lineHeight":{"Mobile":{"point":"70","unit":"px"}}},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-17","right":"","left":"","bottom":""}},"Mobile":{"unit":"%","dimension":{"top":"-158","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"top":"-35"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"zIndex":{"Desktop":"0"},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"default","Tablet":"default"},"positioningAlign":{"Desktop":"center"},"positioningLocation":"default","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":""}},"positioningRight":{"Desktop":{"unit":"%","point":""},"Tablet":{"point":"","unit":"px"},"Mobile":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":""},"Mobile":{"unit":"%","point":""},"Tablet":{"point":"","unit":"px"}},"positioningBottom":{"Mobile":{"unit":"%","point":""}}} /-->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-F92P6u","margin":{"Desktop":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":16.6,"Tablet":33.33,"Mobile":null},"elementId":"guten-zpow0W","horizontalAlign":{"Desktop":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"slideInUp","Mobile":"fadeInDown"},"duration":"normal","delay":"300"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-LfB6C3","imgSrc":{"media":{"imageId":1255,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/wand-magic-sparkles-solid-new.webp","height":89,"width":100,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"wand magic sparkles","captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"height":{"Desktop":{"point":"50","unit":"px"},"Mobile":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-eDt7lm","alignList":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"textColorHover":{"type":"variable","id":"gv-color-text-primary"},"textTypography":{"type":"variable","id":"gv-font-fun-fact-heading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-MZQcYr","url":"#","hasGlobalLink":true,"ariaLabel":"services","hideIcon":true,"text":"Rescue Treatment"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-OHqBih","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}},"padding":{"Tablet":[]},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInUp","Mobile":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-huyC6r","imgSrc":{"media":{"imageId":1254,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/bottle-droplet-solid-new.webp","height":99,"width":62,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"bottle droplet","captionOriginal":"","width":{"Desktop":{"point":"35","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[]}},"imageFit":{"Desktop":"cover"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":[],"Mobile":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-k1nffZ","alignList":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"textColorHover":{"type":"variable","id":"gv-color-text-primary"},"textTypography":{"type":"variable","id":"gv-font-fun-fact-heading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-G11rm6","url":"#","hasGlobalLink":true,"ariaLabel":"services","hideIcon":true,"text":"Scalp Massage"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-P8by1D","margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"slideInUp","Mobile":"fadeInDown"},"duration":"normal","delay":"500"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-YpSkG5","imgSrc":{"media":{"imageId":1253,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/droplet-solid-new.webp","height":107,"width":80,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"droplet solid","captionOriginal":"","width":{"Desktop":{"point":"40","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-qqZt8X","alignList":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"textColorHover":{"type":"variable","id":"gv-color-text-primary"},"textTypography":{"type":"variable","id":"gv-font-fun-fact-heading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-jVTAu9","url":"#","hasGlobalLink":true,"ariaLabel":"services","hideIcon":true,"text":"Body Scrub"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-y9oviT","animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInDown","Mobile":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-dPBzc9","imgSrc":{"media":{"imageId":1252,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/plate-wheat-solid-new.webp","height":100,"width":100,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"plate wheat solid","captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"25","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-gAuerZ","alignList":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"textColorHover":{"type":"variable","id":"gv-color-text-primary"},"textTypography":{"type":"variable","id":"gv-font-fun-fact-heading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-3ILi2x","url":"#","hasGlobalLink":true,"ariaLabel":"services","hideIcon":true,"text":"Natural Mask"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33,"Mobile":null},"elementId":"guten-VoARKT","animation":{"type":{"Desktop":"fadeInUp","Tablet":"fadeInDown","Mobile":"fadeInDown"},"duration":"normal","delay":"700"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-DJ9ONM","imgSrc":{"media":{"imageId":1257,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/hand-sparkles-solid-new.webp","height":80,"width":100,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"hand sparkles","captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"35"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-HyQpjD","alignList":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"textColorHover":{"type":"variable","id":"gv-color-text-primary"},"textTypography":{"type":"variable","id":"gv-font-fun-fact-heading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-SQt1zN","url":"#","hasGlobalLink":true,"ariaLabel":"services","hideIcon":true,"text":"Pranama Stone"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":16.666666666666668,"Tablet":33.33},"elementId":"guten-zH2ogS","margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInDown","Mobile":"fadeInUp"},"duration":"normal","delay":"800"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-Ho0zck","imgSrc":{"media":{"imageId":1256,"sizes":{"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/hand-holding-droplet-solid-new.webp","height":89,"width":100,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"hand holding droplet","captionOriginal":"","width":{"Desktop":{"point":"50","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-CY624m","alignList":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"textColorHover":{"type":"variable","id":"gv-color-text-primary"},"textTypography":{"type":"variable","id":"gv-font-fun-fact-heading","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-KicTLu","url":"#","hasGlobalLink":true,"ariaLabel":"services","hideIcon":true,"text":"Swan Spa"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
