<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 6', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-i8JoSc","background":{"type":"default","color":{"type":"variable","id":"waterlava-secondary"},"videoPlayOnMobile":false},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"50"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"20","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"40","left":"10"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-LqWuxt","margin":{"Tablet":{"unit":"px","dimension":{"left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none","Tablet":"fadeInLeft","Mobile":"fadeInLeft"},"duration":"normal","delay":""}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-2yD06C","content":"Water Lava Service Menu","textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"weight":"600"},"containsAnchorTag":false,"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"slideInLeft"},"duration":"normal","delay":"200"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-EvmBy6","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Mobile":{"unit":"px","dimension":{"bottom":""}},"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Mobile":{"unit":"px","dimension":{"right":"40"}},"Tablet":{"unit":"%","dimension":{"right":"15"}},"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
<!-- wp:paragraph -->
<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisla.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-TpsFS5","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-AXxfxA","margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-r3rmjo","background":{"type":"default","color":{"r":255,"g":252,"b":249,"a":1},"videoPlayOnMobile":false},"margin":{"Tablet":{"unit":"px","dimension":{"top":"20"}},"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}},"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"wrapColumn":{"Desktop":true,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null},"elementId":"guten-qEyHJJ","border":{"radius":{"Desktop":[]},"bottom":{"type":"dashed","width":"1","color":{"type":"variable","id":"waterlava-primary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-qg8Oiv","titleTag":"h3","text":"Sauna Relax","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"waterlava-primary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"subMargin":{"Desktop":[],"Mobile":[]},"subPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"bottom":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"475","unit":"px"},"Tablet":{"point":"1000","unit":"px"},"Mobile":{"point":"1000","unit":"px"}}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-LCVmqV","alignText":{"Desktop":"flex-end"},"titleTag":"h3","text":"$23 ","focusText":" / Hours","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-secondary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10"}}},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null},"elementId":"guten-vcdNVL","border":{"radius":{"Desktop":[]},"bottom":{"type":"dashed","width":"1","color":{"type":"variable","id":"waterlava-primary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"500"}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-76nvn7","titleTag":"h3","text":"Manicure","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"waterlava-primary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"subMargin":{"Desktop":[],"Mobile":[]},"subPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"475","unit":"px"},"Tablet":{"point":"1000","unit":"px"},"Mobile":{"point":"1000","unit":"px"}}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-Y4P7Wt","alignText":{"Desktop":"flex-end"},"titleTag":"h3","text":"$14 ","focusText":" / Hours","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-secondary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10"}}},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null},"elementId":"guten-HEQPam","border":{"radius":{"Desktop":[]},"bottom":{"type":"dashed","width":"1","color":{"type":"variable","id":"waterlava-primary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-ovdlW5","titleTag":"h3","text":"Pedicure","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"waterlava-primary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"subMargin":{"Desktop":[],"Mobile":[]},"subPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"475","unit":"px"},"Tablet":{"point":"1000","unit":"px"},"Mobile":{"point":"1000","unit":"px"}}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-2Qi20g","alignText":{"Desktop":"flex-end"},"titleTag":"h3","text":"$16 ","focusText":" / Hours","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-secondary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10"}}},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null},"elementId":"guten-8c2CiF","border":{"radius":{"Desktop":[]},"bottom":{"type":"dashed","width":"1","color":{"type":"variable","id":"black"}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"700"}} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-dnlsqW","titleTag":"h3","text":"Body Wraps","focusText":"","subText":"Morbi amet convallis","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"focusMargin":{"Desktop":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Mobile":[]},"subColor":{"type":"variable","id":"waterlava-primary"},"subTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"subMargin":{"Desktop":[],"Mobile":[]},"subPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"475","unit":"px"},"Tablet":{"point":"1000","unit":"px"},"Mobile":{"point":"1000","unit":"px"}}} /-->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-S9tisC","alignText":{"Desktop":"flex-end"},"titleTag":"h3","text":"$31 ","focusText":" / Hours","subText":"","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"gv-color-secondary"},"mainTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"mainMargin":{"Desktop":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Mobile":[]},"focusColor":{"type":"variable","id":"gv-color-text-primary"},"focusTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"focusMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"10"}}},"focusPadding":{"Desktop":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-nwHUB1","background":{"type":"default","color":{"r":255,"g":252,"b":249,"a":1}},"backgroundOverlay":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"default"},"repeat":{"Desktop":"default"},"size":{"Desktop":"default"},"color":{"r":255,"g":252,"b":249,"a":1}},"opacity":"0.5","margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"0","bottom":"0","right":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}}} -->
<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-G21plg","verticalAlign":"center","background":{"type":"default","image":{"Desktop":{"id":155,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/tree-nature-branch-blossom-snow-winter-635980-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"r":5,"g":5,"b":5,"a":1}},"opacity":"0.5","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"70","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}}},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"800"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"sectionVerticalAlign":"center","elementId":"guten-8u51Ki","background":{"type":"default","color":{"r":191,"g":164,"b":152,"a":0.71}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"60","left":"60"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"100","left":"100"}}},"animation":{"type":{"Desktop":"fadeIn","Tablet":"fadeIn","Mobile":"fadeIn"},"duration":"normal","delay":"900"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-9p11dV","content":"Get Up To","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"containsAnchorTag":false,"positioningType":{"Desktop":"default","Tablet":"default"},"positioningAlign":{"Tablet":"center"},"positioningLocation":"default","positioningLeft":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningRight":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-mPNOAn","content":"25%","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"style":"italic","weight":"400"},"containsAnchorTag":false,"positioningLocation":"default","positioningLeft":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningRight":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-iqWVSH","content":"Discount","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Mobile":[]},"padding":{"Mobile":[]},"positioningType":{"Desktop":"default"},"positioningLocation":"default","positioningLeft":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningRight":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningTop":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"positioningBottom":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
