<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 1', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-uvZMpK","background":{"type":"default","color":{"type":"variable","id":"waterlava-secondary"},"videoPlayOnMobile":false},"bottomDivider":{"type":"waves","width":{"Desktop":"140","Mobile":"169"},"height":{"Desktop":"90","Tablet":"65","Mobile":"47"},"colorMode":"default","color":{"r":254,"g":254,"b":254,"a":1},"front":true,"flip":false},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"180"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"80"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-VcgnLu"} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-GgkpPT","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"sectionVerticalAlign":"center","elementId":"guten-HJA46S"} -->
<!-- wp:gutenverse/image {"elementId":"guten-fIZCZL","imgSrc":{"media":{"imageId":1248,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/Logo-1-new.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/Logo-1-new.webp","height":200,"width":200,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"logo new","captionOriginal":"","width":{"Desktop":{"point":"124","unit":"px"},"Mobile":{"point":"73","unit":"px"}},"height":{"Mobile":{"point":"72","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"align":{"Desktop":"center"},"imageFit":{"Desktop":"cover"},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-uHZDbV","content":"An Incredible Spa Experience","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"lineHeight":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"46"},"Mobile":{"unit":"px","point":"42"}},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInRight","Mobile":"fadeInRight"},"duration":"normal","delay":"100"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-tTxbfm","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"25.2"}},"weight":"400"},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"zIndex":{"Desktop":"1"},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInDown","Mobile":"fadeInDown"},"duration":"normal","delay":"200"}} -->
<!-- wp:paragraph -->
<p>Duis dictum vestibulum ante vitae ullamcorper. Phasellus ullamcorper odio vitae eleifend ultricies lectus orci congue magna in egestas nulla libero non nisl. Etiam efficitur in arcut lacinia. Donec scelerisque enim non dictum aliquet. Sed ecnunc suspendisse volutpat elit nec nisi congue tristique eu at velit.&nbsp;</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/heading {"elementId":"guten-hfZCos","content":"WaterLava","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-accent-secondary"},"typography":{"font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"point":"150","unit":"px"},"Tablet":{"point":"100","unit":"px"},"Mobile":{"point":"50","unit":"px"}},"weight":"600","transform":"default","spacing":{"Desktop":"0.125"},"lineHeight":{"Mobile":{"point":"50","unit":"px"},"Tablet":{"point":"100","unit":"px"}}},"containsAnchorTag":false,"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"%","dimension":{"top":"-19","right":"0","left":"","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"-157"}},"Mobile":{"unit":"%","dimension":{"top":"-95","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"default","Tablet":"default"},"positioningWidth":{"Tablet":{"unit":"%","point":"100"}},"positioningLocation":"default","positioningLeft":{"Desktop":{"unit":"%","point":""},"Tablet":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"}},"positioningRight":{"Tablet":{"unit":"%","point":""}},"positioningTop":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"","unit":"px"},"Tablet":{"unit":"%","point":""}},"positioningBottom":{"Tablet":{"unit":"%","point":""}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/image {"elementId":"guten-8Zz91Y","imgSrc":{"media":{"imageId":1247,"sizes":{"thumbnail":{"height":122,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/hand-sign.webp","orientation":"landscape"},"medium":{"height":71,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/hand-sign.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/hand-sign.webp","height":122,"width":512,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"hand sign","captionOriginal":"","width":{"Desktop":{"point":"280","unit":"px"},"Mobile":{"point":"174","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Mobile":[],"Tablet":[]}},"align":{"Desktop":"center"},"imageFit":{"Desktop":"default"},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInLeft","Mobile":"fadeInLeft"},"duration":"normal","delay":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Desktop":"10"},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-SWsBfI","content":"WaterLava Owner","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-meta","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"22"}},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal","delay":"400"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
