<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-4qr4Df","background":{"type":"default","image":{"Desktop":{"id":335,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/wood-food-basket-baking-towel-flowers-1060664-pxhere.com_.webp"}},"position":{"Desktop":"top left","Tablet":"center center","Mobile":"center center"},"size":{"Desktop":"cover","Tablet":"cover"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"yposition":{"Tablet":{"point":"1","unit":"px"},"Mobile":{"point":"","unit":"px"}},"xposition":{"Tablet":{"unit":"vh","point":"0.1"},"Mobile":{"unit":"em","point":""}},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-background-overlay"},"gradientColor":[{"color":"rgb(247, 248, 248)","active":false,"opacity":0.53,"id":1,"offset":"0.000"},{"color":"rgb(250, 250, 250)","active":false,"opacity":0,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.8","border":{"radius":{"Tablet":[],"Desktop":[]}},"bottomDivider":{"type":"waves","width":{"Desktop":"144","Tablet":"174"},"flip":false,"height":{"Desktop":"90","Tablet":"100"},"colorMode":"default","color":{"r":255,"g":252,"b":249,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"0","top":"0","left":"0","right":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"200"}},"Tablet":{"unit":"px","dimension":{"top":"150","bottom":"200","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"150","bottom":"200"}}},"animation":{"type":{"Desktop":"none"}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-3vgI6y"} -->
<!-- wp:gutenverse/heading {"elementId":"guten-q3mXI6","content":"404","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-heading-404","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"unit":"px","point":"200"},"Tablet":{"unit":"px","point":"190"},"Mobile":{"unit":"px","point":"120"}},"lineHeight":{"Desktop":{"unit":"px","point":"200"},"Tablet":{"unit":"px","point":"190"},"Mobile":{"unit":"px","point":"120"}},"style":"italic","weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"fadeInDown","Mobile":"fadeInDown"},"duration":"slow","delay":"1"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-acrOQB","content":"Something Went Wrong","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"style":"italic","weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"-40"}},"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"20"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp","Tablet":"fadeInDown","Mobile":"fadeInDown"},"duration":"slow","delay":"1"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-kxbE7L","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"px","point":"28.8"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"120","top":"0","bottom":"0","left":"120"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInDown","Tablet":"fadeInUp","Mobile":"slideInUp"},"duration":"slow","delay":"2"}} -->
<!-- wp:paragraph -->
<p>Quisque consectetur convallis exquis tincidunt ligula placeratet. Nam quis leo sed tortor blandit commodo. Quisque ultrices justo non convallis accumsan ante magna ornare sapien quis venenatis diam libero necorci.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"elementId":"guten-DPwJel","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-HIN6fa"} -->
<!-- wp:gutenverse/button {"elementId":"guten-i0nEgV","content":"Back To Home","alignButton":{"Desktop":"center","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"25","bottom":"25","right":"40","left":"40"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":2,"g":1,"b":1,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-secondary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"white"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"all":{"type":"solid","color":{"type":"variable","id":"gv-color-secondary"},"width":"1"}},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"slow","delay":"3"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"12"}},"spacing":{"Desktop":"0.125"},"transform":"uppercase","weight":"400"},"hoverTextColor":{"type":"variable","id":"white"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
