<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Single Hero', 'waterlava' ),
	'categories' => array( 'waterlava-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-4qr4Df","verticalAlign":"center","background":{"type":"default","image":{"Desktop":{"id":161,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_XVEZDYZASS.webp"}},"position":{"Desktop":"center center","Tablet":"center center","Mobile":"center center"},"size":{"Desktop":"cover","Tablet":"cover"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat"},"yposition":{"Tablet":{"point":"1","unit":"px"},"Mobile":{"point":"","unit":"px"}},"xposition":{"Tablet":{"unit":"vh","point":"0.1"},"Mobile":{"unit":"em","point":""}},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-background-overlay"},"gradientColor":[{"color":"rgb(247, 248, 248)","active":false,"opacity":0.53,"id":1,"offset":"0.000"},{"color":"rgb(250, 250, 250)","active":false,"opacity":0,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.7","topDivider":{"colorMode":"default","color":{"r":255,"g":255,"b":255,"a":1}},"bottomDivider":{"type":"waves","width":{"Desktop":"144"},"flip":false,"height":{"Desktop":"99","Mobile":"71"},"colorMode":"default","color":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"200","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"150","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"100","bottom":"150","right":"10","left":"10"}}},"animation":{"type":{"Desktop":"none"}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sectionVerticalAlign":"center","elementId":"guten-3vgI6y","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"flex-start"},"margin":{"Tablet":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
<!-- wp:gutenverse/post-title {"elementId":"guten-BoThEm","alignment":{"Desktop":"center","Tablet":"center"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Alex Brush","value":"Alex Brush","type":"google"},"size":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"lineHeight":{"Desktop":{"unit":"px","point":"100"},"Tablet":{"unit":"px","point":"80"},"Mobile":{"unit":"px","point":"48"}},"style":"italic","weight":"400"},"color":{"type":"variable","id":"white"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"10","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element guten-post-title guten-BoThEm"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/icon {"elementId":"guten-JPXaCb","icon":"far fa-user","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMwNCAxMjhhODAgODAgMCAxIDAgLTE2MCAwIDgwIDgwIDAgMSAwIDE2MCAwek05NiAxMjhhMTI4IDEyOCAwIDEgMSAyNTYgMEExMjggMTI4IDAgMSAxIDk2IDEyOHpNNDkuMyA0NjRIMzk4LjdjLTguOS02My4zLTYzLjMtMTEyLTEyOS0xMTJIMTc4LjNjLTY1LjcgMC0xMjAuMSA0OC43LTEyOSAxMTJ6TTAgNDgyLjNDMCAzODMuOCA3OS44IDMwNCAxNzguMyAzMDRoOTEuNEMzNjguMiAzMDQgNDQ4IDM4My44IDQ0OCA0ODIuM2MwIDE2LjQtMTMuMyAyOS43LTI5LjcgMjkuN0gyOS43QzEzLjMgNTEyIDAgNDk4LjcgMCA0ODIuM3oiLz48L3N2Zz4=","iconAlign":{"Tablet":"center"},"iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"10"},"iconColorTwo":{"type":"variable","id":"white"},"iconShape":"custom","margin":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"left":"10"}}},"padding":{"Tablet":{"unit":"%","dimension":{"left":"30","right":""}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-author {"elementId":"guten-DTfkFX","typography":{"type":"variable","id":"post-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"px","point":"18"}},"weight":"400"},"color":{"type":"variable","id":"white"},"authorBorder":{"radius":{"Desktop":[]}},"authorBorderResponsive":{"Desktop":{"radius":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-author guten-DTfkFX"></div>
<!-- /wp:gutenverse/post-author -->

<!-- wp:gutenverse/icon {"elementId":"guten-DX3Gvh","icon":"far fa-calendar","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTE1MiAyNGMwLTEzLjMtMTAuNy0yNC0yNC0yNHMtMjQgMTAuNy0yNCAyNFY2NEg2NEMyOC43IDY0IDAgOTIuNyAwIDEyOHYxNiA0OFY0NDhjMCAzNS4zIDI4LjcgNjQgNjQgNjRIMzg0YzM1LjMgMCA2NC0yOC43IDY0LTY0VjE5MiAxNDQgMTI4YzAtMzUuMy0yOC43LTY0LTY0LTY0SDM0NFYyNGMwLTEzLjMtMTAuNy0yNC0yNC0yNHMtMjQgMTAuNy0yNCAyNFY2NEgxNTJWMjR6TTQ4IDE5Mkg0MDBWNDQ4YzAgOC44LTcuMiAxNi0xNiAxNkg2NGMtOC44IDAtMTYtNy4yLTE2LTE2VjE5MnoiLz48L3N2Zz4=","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"10"},"iconColorTwo":{"type":"variable","id":"white"},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-date {"elementId":"guten-x55IKW","typography":{"type":"variable","id":"post-font","font":{"label":"Eb Garamond","value":"Eb Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"px","point":"18"}},"weight":"400"},"color":{"type":"variable","id":"white"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"%","dimension":{"right":"29","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-post-date guten-x55IKW"></div>
<!-- /wp:gutenverse/post-date -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
